name: Labeling new issue
on:
  issues:
    types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: SomayaB/auto-label@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          labels-synonyms: '{"ec2":["ec2","elastic cloud computing"],"ecr":["ecr", "elastic container registry"],"question":["help"]}'
          labels-not-allowed: '["good first issue"]'
          default-labels: '["needs-triage"]'
