name: "Set Issue Label and Assignee"
on:
 issues:
    types: [opened, edited]
 pull_request:
    types: [opened, edited]
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps: 
     - with:
          keywords-assignees-labels: '[ {"keywords": ["ecr"], "labels": ["ecr"], "assignees": ["SomayaB"]}, {"keywords": ["ec2"], "labels": ["ec2"], "assignees": ["SomayaB"]}]'
          title-or-body: 'title'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
       uses: SomayaB/issue-action@1d6c0d5
