name: "Set Issue Label and Assignee"
on:
 issues:
    types: [opened, edited]
 pull_request:
    types: [opened, edited]
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps: 
     - with:
          title-or-body: 'title'
          parameters: '[ {"keywords": ["ecr", "elastic container registry"], "labels": ["red"], "assignees": ["SomayaB"]}, {"keywords": ["ec2"], "labels": ["ec2"], "assignees": ["SomayaB"]}, {"keywords": ["@aws-cdk/aws-route53-patterns", "aws-route53-patterns", "route53-patterns", "route53 patterns"], "labels": ["@aws-cdk/aws-route53-patterns"], "assignees": ["SomayaB"]}, {"keywords": ["@aws-cdk/aws-route53", "aws-route53", "route53"], "labels": ["@aws-cdk/aws-route53"], "assignees": ["SomayaB"]} ]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
       uses: SomayaB/issue-action@a93e974
