name: "Set Assignee"
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["ec2"]'
          assignees: '["SomayaB"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
