name: "Set Issue Label and Assignee"
on:
 issues:
    types: [opened, edited]
 pull_request:
    types: [opened, edited]
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps: 
     - with:
          keywords: '["ec2"]'
          labels: '["ec2"]'
          assignees: '["SomayaB"]'
          title-or-body: 'both'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
       uses: SomayaB/issue-action@608d83f
     - with:
          keywords: '["ecr"]'
          labels: '["ecr"]'
          assignees: '["SomayaB"]'
          title-or-body: 'title'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
       uses: SomayaB/issue-action@608d83f
     - with:
          keywords: '["route53", "route 53"]'
          labels: '["package/route53"]'
          assignees: '["SomayaB"]'
          title-or-body: 'title'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
       uses: SomayaB/issue-action@608d83f
