name: "Set Issue Label"
on:
 issues:
    types: [opened]
 pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps: 
     - name: Checkout
       uses: actions/checkout@v2
       with:
         repository: SomayaB/issue-action
         ref: 00b6159
         token: "${{ secrets.GITHUB_TOKEN }}"
     - with:
          keywords: '["ec2"]'
          labels: '["ec2"]'
          assignees: '["SomayaB"]'
     - with:
          keywords: '["ecr"]'
          labels: '["ecr"]'
          assignees: '["moniarchy"]'
     - with:
          keywords: '["route53", "route 53"]'
          labels: '["package/route53"]'
          assignees: '["SomayaB"]'
